name: flutter_dropzone_web
description: A drag-and-drop Flutter plugin (Web only).
version: 3.0.13
homepage: https://github.com/deakjahn/flutter_dropzone

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_dropzone_platform_interface: ^2.0.6
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  flutter_dropzone_platform_interface:
    path: ../flutter_dropzone_platform_interface

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterDropzonePlugin
        fileName: flutter_dropzone_plugin.dart

  assets:
    - packages/flutter_dropzone_web/assets/flutter_dropzone.js
