name: flutter_dropzone
description: A drag-and-drop Flutter plugin (Web only).
version: 3.0.7
homepage: https://github.com/deakjahn/flutter_dropzone

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dropzone_platform_interface: ^2.0.6
  flutter_dropzone_web: ^3.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  plugin_platform_interface: ^2.0.0

dependency_overrides:
  flutter_dropzone_platform_interface:
    path: ../flutter_dropzone_platform_interface
  flutter_dropzone_web:
    path: ../flutter_dropzone_web

flutter:
  plugin:
    platforms:
      web:
        default_package: flutter_dropzone_web
